development:
  adapter: postgresql
  database: vzgojiteljica-development
  username: postgres
  host: boot2docker

test:
  adapter: postgresql
  database: vzgojiteljica-test
  username: postgres
  host: boot2docker
