development:
  adapter: postgresql
  database: vzgojiteljica-development
  username: postgres
  host: docker

test:
  adapter: postgresql
  database: vzgojiteljica-test
  username: postgres
  host: docker