#config/schedule.yml

invoices_due:
  cron: "0 16 * * *"
  class: "InvoicesDueEmailerWorker"
  queue: default

invoices_due_to_customer:
  cron: "0 6 * * *"
  class: "InvoicesDueToCustomerEmailerWorker"
  queue: default
